SELECT * FROM EMPLOYEE WHERE SALARY > 50000;

SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 40000 AND 70000;

SELECT * FROM EMPLOYEE WHERE SALARY < 30000;

SELECT * FROM EMPLOYEE WHERE SALARY >= 60000;

SELECT * FROM EMPLOYEE WHERE SALARY <> 45000;

SELECT * FROM EMPLOYEE WHERE DEPARTMENT = 'IT';

SELECT * FROM EMPLOYEE WHERE DEPARTMENT != 'HR';
